// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:70ae5cb0-8bb0-40ed-9d2e-3052fe71983e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LL1T6C8Pe",
    "aws_user_pools_web_client_id": "64n1t7brtkcs74knqom42drqrs"
};


export default awsmobile;
